server:
  port: 9003
  ##eureka-server2节点配置，配置参数--spring.profiles.active=eureka-server1来启动该环境
spring:
  profiles: eureka-server2
eureka:

  #eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetchRegistry: false
    #设置与Eureka Server交互的地址
    #查询服务和注册服务都需要依赖这个地址。
    #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl:
      defaultZone:  http://eureka-server1:9002/eureka/
  instance:
    hostname: eureka-server2