#服务端口
server:
  port: 9001
spring:
  application:
    #服务对应名称
    name: sc-eurka-server
#eurekak对应路径
eureka:
  instance:
    hostname: localhost
  #Eureka 有自我保护机制，通过在Eureka Server配置如下参数，可启动保护机制。
  server:
    enable-self-preservation: true
  #eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetchRegistry: false
    #服务路径
    serviceUrl:
      #设置与Eureka Server交互的地址
      #查询服务和注册服务都需要依赖这个地址。
      #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
