server:
  port: 9010
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: https://github.com/SoulKingdom/SpringCloudLearn/
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: config-repo
          # git仓库的账号
          username: SoulKingdom
          # git仓库的密码
          password: mm609130
