#服务端口
server:
  port: 9008
spring:
  application:
    #服务对应名称
    name: sc-ribbon
eureka:
  client:
    #调用服务
    serviceUrl:
      #设置与Eureka Server交互的地址
      #查询服务和注册服务都需要依赖这个地址。
      #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:9001/eureka/